version: '3'

services:
  app:
    build: .
    image: ct-dev
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_SECRETS_MANAGER_KEY: ${AWS_SECRETS_MANAGER_KEY}
      AWS_SECRETS_MANAGER_SECRET_ACCESS_KEY: ${AWS_SECRETS_MANAGER_SECRET_ACCESS_KEY}
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      RAILS_ENV: development
      http_proxy: http://web-proxy.austin.hpicorp.net:8080
      https_proxy: http://web-proxy.austin.hpicorp.net:8080
      SECRET_KEY_BASE: ABC
    volumes:
      - ./:/app
      - .ssl:/app/.ssl
      - bundle:/bundle
      - ~/.aws:/root/.aws:ro
    ports:
      - "3000:3000"
volumes:
  bundle:
    driver: local
